### PR TITLE
feat: live loading of bot.json (#20)

### PR DESCRIPTION
**Pull request by lucas-engen**
Signed-off-by: Lucas Vieira <lucas.engen.cc@gmail.com>

### CODE REVIEW

**Comment by prakhargurunani** [comment]
@lucas-engen Please show a GIF whether this works.

**Comment by lucas-engen** [comment]
live-reloading


> @lucas-engen Please show a GIF whether this works.

**Review by prakhargurunani — APPROVED** [review]
Nice work ! :rocket:

**Comment by prakhargurunani** [comment]
@vasani-arpit Ready to merge

**Comment by lucas-engen** [comment]
> Nice work ! 🚀

Thanks ! 💪

**Comment by lucas-engen** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

@vasani-arpit

**Review by prakhargurunani — APPROVED** [review]

**Review by prakhargurunani — APPROVED** [review]
@vasani-arpit Merge

**Comment by vasani-arpit** [comment]
@prakhargurunani I have merged this to master. Download latest binary and check everything is fine or not.

**Comment by prakhargurunani** [comment]
@vasani-arpit Everything is working. `bot.json` live reloading is also functional.
fixes: #20 

**Enhancement**: Upon closing the chromium window directly, the API makes a request which is unhandled by WBOT, throwing an error ⏬ 
```bash
(node:1820) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.cal
    at send.Promise (/snapshot/workspace/node_modules/puppeteer-core/lib/Connect
    at new Promise (<anonymous>)
    at CDPSession.send (/snapshot/workspace/node_modules/puppeteer-core/lib/Conn
    at ExecutionContext.evaluateHandle (/snapshot/workspace/node_modules/puppete
    at ExecutionContext.<anonymous> (/snapshot/workspace/node_modules/puppeteer-
    at WaitTask.rerun (/snapshot/workspace/node_modules/puppeteer-core/lib/DOMWo
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/snapshot/workspace/node_modules/puppeteer-core/lib/he
    at Page.waitForSelector (/snapshot/workspace/node_modules/puppeteer-core/lib
    at setupSmartReply (/snapshot/workspace/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This 
(node:1820) [DEP0018] DeprecationWarning: Unhandled promise rejections are depreciated.
```

It may be confusing for some users. It would be better that WBOT displays a warning of what actually happened.

**Comment by vasani-arpit** [comment]
@prakhargurunani thanks for pointing that. Will fix that in upcoming patch update.

**Pull request merged**
