### PR TITLE
Create a seperate popup page for some features [0.25.0]

### PR DESCRIPTION
**Pull request by nikhilmaske-2001**
**TODOs:**
1. Call function `setupFeaturePage()` without opening the chat

This PR contains the following changes:
1. Implemented new privacy features like Blur Name, blur chats, blur photos and blur recent messages
2. Dark mode feature
3. Improved the color combination of smartreply suggestion button (now it matches with chat bubble)

GIF:
complete

### CODE REVIEW

**Comment by nikhilmaske-2001** [comment]
@vasani-arpit Look at the above gif and if you have any suggestions please suggest. This PR is almost ready, just need to add some changes mentioned above in TODOs.

**Comment by vasani-arpit** [comment]
Looks good. Will check it in my local.

**Comment by nikhilmaske-2001** [comment]
@vasani-arpit This PR is completed and I have tested it thoroughly and It can be merge now.
But It has some minor bugs, they are as follows: 
1. Blur chats feature only works for a single chat window, if we change the chat window blur chat feature will be unchecked.
2. Blur chat/photo/name feature only blurs the currently visible text, the chat which is above or below the current window does not blur

**Comment by vasani-arpit** [comment]
- [ ] Blur name is blurring both name and chat
- [ ] Blur chat is doing nothing 
- [ ] If you blur the name and then scroll the chat list then you will see that for some contacts blur is not being applied

**Comment by nikhilmaske-2001** [comment]
@vasani-arpit I will fix the 1st & 2nd issues. 
I am already aware of the 3rd issue and trying to fix it, but I am not able to find the solution for it. 

I am sure the code targets all the required elements we want to blur, but I am not able to understand why does that css property `filter: blur(4px)` does not work on them. 
If you want to debug by yourself, just go through any `blur...` function and `console log` the elements that we are picking using 'getElement',

**Comment by nikhilmaske-2001** [comment]
@vasani-arpit This PR is ready for another review. Please take a look.
There is a bug in Blur name feature, it blurs both name and recent messages chat. I have tried to solve this bug but I didn't find any solution for it. This is because Contact names does not have any unique class/id after an web update maybe, due to this blur name is also not working on [WA plus extension](https://wawplus.com/en/changelog?v=4.8.5)

**Pull request merged**
