### PR TITLE
WIP: Added QR - Refreshes display

### PR DESCRIPTION
**Pull request by tavoarcila**
I'm a very new to node and I think this is not the best way to do it but it currently works, Maybe with this start you can make a better working process...

### CODE REVIEW

**Comment by vasani-arpit** [comment]
Thanks you @tavoarcila. This has been in my todo list for while. Your logic is good but it highly relies on static value like timeoutWait(20) and MaxQRattemps(5). If WA decide to change any of that value then we need to re think the whole logic again and update the code accordingly. 

So, I am suggesting to make the code more rely on elements rather than static waits and flags. so, when ever WA page changes any element related to QR we catch it using MutationObserver and update the QR in CLI. 

Luckily MutationObserver is being used in smart-reply so you can take reference of it and see how it is catching the changes in page and reacts accordingly. 

Thanks !!

**Comment by Saturnych** [comment]
var selector = "img[alt='Scan me!']"; 
await page.evaluate(`
            var MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver,
            config = {
              attributes: true,
              attributeFilter: ['src']
            },
            target = document.querySelector("${selector}");
            var observer = new MutationObserver(function(mutations) {
              mutations.forEach(function(mutation) {
                  window.doQR(mutation.target.src);
              });
            });
            observer.observe(target, config); 
`);

**Comment by Saturnych** [comment]
window.doQR(); // shows new QR

**Comment by vasani-arpit** [comment]
Conflicting changes due to #96. Closing for now. Create new if needed.

**Pull request closed without merging**
