### PR TITLE
Added php snippet  for WebHook in Docs

### PR DESCRIPTION
**Pull request by PvtSec**

### CODE REVIEW

**Comment by Masagung0805** [comment]
i try this files webhook with php can't run?

**Comment by vasani-arpit** [comment]
@PvtSec 
Thanks for the PR. This was much needed. 

Readme file is becoming lengthy to read. can you add the docs here ? https://github.com/vasani-arpit/WBOT/blob/master/docs/Webhook-example.md

and then just reference/link it in the readme file.

**Comment by PvtSec** [comment]
@vasani-arpit 
I think I have added it to the exact file you mentioned. Kindly recheck it.

**Comment by PvtSec** [comment]
@Masagung0805 
Could you elaborate the error you encountered with?

**Comment by z3nth10n** [comment]
> @Masagung0805
> Could you elaborate the error you encountered with?

I tried it too. But it didn't work. As @Masagung0805 stated, there isn't any response from the webhook. The bot just stucks in checking the message.

**Pull request merged**
