### PR TITLE
do not activate webhook by default

### PR DESCRIPTION
**Pull request by gnadelwartz**
Webhook query is done by default and in your default config all messages are sent to ```https://lazy-cow-87.localtunnel.me/api/messages``` .

Send all messages by default to a unknown remote service is at best a privacy risc.

Even the user knows and removes the adress, an webapi query is done and an error is thrown.

So I implemented the switch ```webapi``` with a default value of ```false```. The webhook URL can stay, but the query is disabled by default.

### CODE REVIEW

**Comment by vasani-arpit** [comment]
This was much needed because I created that feature in so rush that I forgot to add that mechanism. we may need to rename things. `webapi`  to `webhook` and `webhook` to` webhookurl`

**Comment by gnadelwartz** [comment]
I was thinking about renaming, but don't like breaking existing Setups ...

**Comment by vasani-arpit** [comment]
Yes. Lot of things requires refactoring. This problem makes it less extendable for adding new features. I am thinking about compartmentalizing useless code and focus on features. 

Let's do that in separate branch.

**Comment by vasani-arpit** [comment]
The PR had conflicts so I am not merging it but I have added this feature into the code. Thanks !!

**Pull request closed without merging**
