### PR TITLE
Fix Send Image

### PR DESCRIPTION
**Pull request by andersondeoliveiramachado**
in sending messages with attached images the sending was stopped.

Search for all occurrences of mediaCollection and replace:

var mc = new Store.MediaCollection();
to
var mc = new Store.MediaCollection(chat);

### CODE REVIEW

**Comment by joweste** [comment]
Pleaae fix It again. Yeaterday it stops to working

**Comment by catur515** [comment]
Not working anymore.. please help.. fix it again..

**Comment by catur515** [comment]
**I found this.. and its working like a charm...**
https://github.com/mukulhase/WebWhatsapp-Wrapper/commit/69c587fd38f727ad0e13f54eb8de003485bad4c6

**Comment by vasani-arpit** [comment]
@catur515 It will last until WA's next update 😀

**Pull request merged**
