### PR TITLE
readme navigation links not working - fixed

### PR DESCRIPTION
**Pull request by mnomanmemon**
readme navigation links such as #preview, #features, #downloads, #technologies was not working. I fixed them

### CODE REVIEW

**Comment by vasani-arpit** [comment]
Thanks. appreciate it.

**Comment by mnomanmemon** [comment]
My pleasure. Will be glad if you merge this PR. Thanks

**Comment by mnomanmemon** [comment]
Hi @vasani-arpit , Can you please merge this so that I can be able to see that PR merged in my hacktoberfest profile. Will be very thankful if you do that :)

**Comment by vasani-arpit** [comment]
I need to update the version in package.json in your PR otherwise GH Action will fail. Haven't had a time to do that.

**Comment by mnomanmemon** [comment]
Okay. Sure thing. Please try to make it soon, thanks!

**Pull request merged**
