### PR TITLE
Get preferred chromium revision

### PR DESCRIPTION
**Pull request by MAZETAM**
Get preferred chromium revision

### CODE REVIEW

**Comment by vasani-arpit** [comment]
Thanks, I wanted to do this for so long. I couldn't figure out how.

**Comment by vasani-arpit** [comment]
This is a good idea but this can cause problems as the revision numbers are different all across OSs. 

So, If Binaries(for all platform) are created from windows PC then I think it will show a number equivalent to windows which can result in error in other OS then windows.

What do you think? @MAZETAM

**Comment by MAZETAM** [comment]
@vasani-arpit 
I was try it only on Windows 10, never try to other OS
Have you try it on other OS?

**Comment by vasani-arpit** [comment]
Closing for now as there is no direct solution to this problem at the moment.

**Pull request closed without merging**
